```{r}
library("tximport")
library("readr")
library("DESeq2")
library(data.table)
```

```{r}
# First lets list all of the quant.sf files
cwd <- getwd()
quant_fp <- paste(cwd, 'quants/', sep = '/')

quant_files <- list.files(path = quant_fp, pattern="quant.sf$", recursive = TRUE)
```

```{r}
# And we can then extract the sample names.
quant_dirs <- list.files(quant_fp, pattern = "_quant$", full.names = TRUE)
sample_names <- gsub("_quant$", "", basename(quant_dirs))
# correct for the FASTQ generation file included in the directory.
sample_names <- sample_names[1: 48]
```

```{r}
# And now we can create the txi import, note that it can take an array of file names.
txi <- tximport(paste(cwd, "quants", quant_files, sep='/'), type = "salmon", txOut = TRUE)
```

```{r}
# Here we will create a temporary Dataframe for the TXI data so that we can add the sample names as columns.
# Before feeding to DESeq2 we need to convert back to a numeric matrix.
atts <- attributes(txi)
data <- data.table(data = txi$counts) # Using DaRMDtaTables allows for better performance
name_list <- attributes(txi)

colnames(data) <- sample_names
```

```{r}
# Extract the conditions from the file names supplied by Jen
#temp <- sub(pattern ="ATEY090523-", "",sample_names)

 # Set experimental conditons
type <- "single-read" # Set Read conditions
condition <- sub(pattern ="_L.*", "", sample_names)
coldata <- data.frame(condition, type)
rownames(coldata) <- sample_names
```

```{r}
# According to the DESeq2 vignette the above code results in a conditions matrix for which the ordering is not the same as the samples.
# It is important to resolve this issue
# This does not seem to be true for our data but its good to make sure.
# We also need to make sure that the coldata labels match the counts data.

head(coldata, 5)
```

```{r}
all(rownames(coldata) %in% colnames(data)) # Ensure that all samples are present in both the data and coldata.
```

```{r}
all(rownames(coldata)==colnames(data)) # Ensure they are in the right order
```

```{r}
# first create the design formula

# Now create the DESeq2 Dataset`

dds = DESeqDataSetFromMatrix(round(data), colData = coldata, design = ~ condition)


```

```{r}
dds <- DESeq(dds)
```

```{r}
res <- results(dds)

```

```{r}
plotMA(res, ylim=c(-10,10))
```

```{r}
resOrdered <- res[order(res$pvalue),]
```

```{r}
write.csv(as.data.frame(resOrdered), "datacsv.csv")
```
